### ISSUE TITLE
How to append the contents of dracula-toolbar.ini to ~/.xournalpp/toolbar.ini

### ISSUE THREAD

**Issue by EmmanuelAmeyaw** [tim-clifford/dracula-xournalpp#2]
How to append when access to toolbar.ini is denied?

```
(base) kofi@kofi-U52F:/usr/share/xournalpp/ui$  /usr/share/xournalpp/ui/toolbar.ini
bash: /usr/share/xournalpp/ui/toolbar.ini: Permission denied
```

**Comment by vicnetto** [comment]
Hey @EmmanuelAmeyaw!

I don't know know what linux distro you're on, but this path (/usr/share/xournalpp/ui) is where the default config files are stored, so you shouldn't change any of this. In my case, I found a configuration folder of xournal++ inside the .config folder.

**My xournalapp folder**: ~/.config/xournal/

(This was in my case, but maybe your config xournal file is in the main user directory, like: ~/.xournal)

Then you should place the file inside this folder, and select the toolbar inside the app.

**Comment by eleanor-clifford** [comment]
Thanks @vicnetto
